version: '3.3'

services:
   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "18080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: redhat

   db: 
     image: mysql:5.6
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: redhat
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: redhat
